@startuml

class MainFrame{
    - size:Dimension
    -position = Point
    - defaultSize:Rectangle 
    - settings:Settings
     - configurationpPanel = ConfigurationPanel;
    - board:Board
}

@enduml